# https://docs.travis-ci.com/user/languages/minimal-and-generic/
language: minimal

env:
  - RCHECK_KEEP_IT_100=1

services:
  - docker

branches:
  only:
    - master

install:
  - curl -sSL https://raw.githubusercontent.com/acidgenomics/Rcheck/master/install | bash

jobs:
  include:
    - stage: test
      name: "bioc-release"
      script: tag="bioc-release" ./.Rcheck/docker
    - stage: test
      name: "bioc-devel"
      script: tag="bioc-devel" ./.Rcheck/docker

matrix:
  allow_failures:
    - name: "bioc-devel"
  fast_finish: true

after_failure:
  - ./.Rcheck/docker-failure

notifications:
  email:
    recipients:
      - mike@steinbaugh.com
    on_success: change
    on_failure: change
